name: eux-saksbehandler
ingress: https://eux-saksbehandler.intern.nav.no

database:
  name: eux-saksbehandler-db-q2
  tier: db-custom-1-3840

cluster:
  fss: prod-fss
  gcp: prod-gcp

application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 512Mi

replicas:
  min: 2
  max: 3
